# Generated by Django 5.2.6 on 2025-10-12 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('especialidad', models.CharField(db_column='ESPECIALIDAD', max_length=100)),
            ],
            options={
                'db_table': 'especialista',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(db_column='FECHA_NACIMIENTO')),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=100, null=True)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(db_column='RUT', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('apellido', models.CharField(db_column='APELLIDO', max_length=100)),
                ('correo', models.CharField(db_column='CORREO', max_length=100, unique=True)),
                ('contrasena', models.CharField(db_column='CONTRASENA', max_length=100)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('motivo', models.CharField(db_column='MOTIVO', max_length=255)),
                ('sintomas', models.CharField(blank=True, db_column='SINTOMAS', max_length=255, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, db_column='FECHA_INICIO', null=True)),
                ('diagnostico', models.CharField(blank=True, db_column='DIAGNOSTICO', max_length=255, null=True)),
                ('fk_idespecialista', models.ForeignKey(blank=True, db_column='FK_IDESPECIALISTA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webEmergencia.especialista')),
                ('fk_idpaciente', models.ForeignKey(db_column='FK_IDPACIENTE', on_delete=django.db.models.deletion.DO_NOTHING, to='webEmergencia.paciente')),
            ],
            options={
                'db_table': 'consulta',
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='fk_rut',
            field=models.OneToOneField(db_column='FK_RUT', on_delete=django.db.models.deletion.DO_NOTHING, to='webEmergencia.persona'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='fk_rutp',
            field=models.OneToOneField(db_column='FK_RUTP', on_delete=django.db.models.deletion.DO_NOTHING, to='webEmergencia.persona'),
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('medicacion', models.CharField(db_column='MEDICACION', max_length=100)),
                ('instruccion', models.CharField(db_column='INSTRUCCION', max_length=255)),
                ('control', models.CharField(blank=True, db_column='CONTROL', max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, db_column='FECHA_REGISTRO', null=True)),
                ('dispositivo', models.CharField(blank=True, db_column='DISPOSITIVO', max_length=100, null=True)),
                ('fk_idpac', models.ForeignKey(db_column='FK_IDPAC', on_delete=django.db.models.deletion.DO_NOTHING, to='webEmergencia.paciente')),
            ],
            options={
                'db_table': 'seguimiento',
            },
        ),
    ]
