# Generated by Django 5.2.6 on 2025-10-12 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webEmergencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fk_idespecialista',
            field=models.ForeignKey(blank=True, db_column='FK_IDESPECIALISTA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultas', to='webEmergencia.especialista'),
        ),
    ]
