# Generated by Django 5.2.6 on 2025-10-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webEmergencia', '0002_alter_consulta_fk_idespecialista'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='especialidad',
            field=models.CharField(db_column='ESPECIALIDAD', default='Medicina General', max_length=100),
        ),
    ]
