# Generated by Django 5.2.6 on 2025-11-11 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webEmergencia', '0003_consulta_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='especialista_asignado',
            field=models.ForeignKey(blank=True, db_column='ESPECIALISTA_ASIGNADO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to='webEmergencia.especialista'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('cancelada', 'Cancelada'), ('aplazada', 'Aplazada')], db_column='ESTADO', default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='consulta',
            name='razon_cancelacion',
            field=models.TextField(blank=True, db_column='RAZON_CANCELACION', null=True),
        ),
    ]
