# Generated by Django 5.2.6 on 2025-11-29 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webEmergencia', '0004_consulta_especialista_asignado_consulta_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('cancelada', 'Cancelada'), ('aplazada', 'Aplazada'), ('finalizada', 'Finalizada')], db_column='ESTADO', default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(db_column='DESCRIPCION')),
                ('es_cronico', models.BooleanField(db_column='ES_CRONICO', default=False)),
                ('nombre_enfermedad', models.CharField(blank=True, db_column='NOMBRE_ENFERMEDAD', max_length=255, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, db_column='FECHA_EMISION')),
                ('consulta', models.OneToOneField(db_column='FK_CONSULTA', on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico_data', to='webEmergencia.consulta')),
            ],
            options={
                'db_table': 'diagnostico',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('medicamento', models.CharField(db_column='MEDICAMENTO', max_length=255)),
                ('dosis', models.CharField(db_column='DOSIS', max_length=255)),
                ('horario', models.CharField(db_column='HORARIO', max_length=255)),
                ('diagnostico', models.ForeignKey(db_column='FK_DIAGNOSTICO', on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='webEmergencia.diagnostico')),
            ],
            options={
                'db_table': 'receta',
            },
        ),
    ]
